---
title: "Teaching"
---
## Teaching Experiences

After realizing I was 'decent at math' I sought to be a high school math teacher. However, early in my undergraduate career I quickly fell in love with research and subsequently pursued research experiences and graduate school. Fortunately the 'teaching bug' has never left, I received an undergraduate minor in Education and in my PhD, I enjoyed TA-ing several classes and teaching numerous workshops. As a postdoc, I continue to teach 

* Teaching assistant experiences: 
  + Calculus Analysis for Biologists -University of Washington
  + Calculus I -Houghton College
  + Calculus II -Houghton College
  + Calculus for the life sciences -Houghton College
  + Math explorations: Mathematics and Music -Houghton College
  + Biodiversity -Houghton College
  
* Workshop teaching experiences: 
  + [An overview of Structured Decision Making for natural resources -Missouri Natural Resources Conference 2025](https://briellekwarta19.github.io/SDMworkshop_MNRC_2025/)
  + [An overview of Structured Decision Making for natural resources -Midwest Fish and Wildlife Conference 2025](https://briellekwarta19.github.io/SDMworkshop_MidwestFW_2025/)
  + Fundamentals of Structured Decision Making - The Wildlife Society Conference 2023
  + Overview of Structured Decision Making: A primer on Value-Focused Thinking - Washington Department of Fish and Wildlife 2022 & 2023
   + [Introduction to spatial data in R](https://github.com/briellekwarta19/makingmaps_QERM597) - University of Washington 
  + [Git and Github for the scientific programmer](https://github.com/briellekwarta19/GSS-github-workshop) - University of Washington 2021
  
* Guest lecture/facilitating experiences: 
  + Facilitator- FW 8001: Perspectives for Emerging Professionals, University of Missouri 2025
  + Lecture- FISH 507: Introduction to Structured Decision Making, University of Washington 2023
  + Lecture- QERM 597: Quantitative Ecology Seminar, University of Washington 2020-2022

